spring.application.name=ecommerce

server.port=8080

# PostgreSQL設定
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JWT設定
#至少32bytes長度
app.jwt.secret=your-secret-key

#60*60*1000 = 1hr
app.jwt.expiration-ms=3600000
